sudo: false
language: php

jobs:
  include:
    - php: 7.4

cache:
  directories:
    - vendor

before_script:
  - travis_retry composer install --no-interaction --no-suggest
  - cp .env.example .env
  - php artisan key:generate

script:
  - php artisan test
